"""Single source of truth for risk codes emitted by the workbench.

Every code emitted as a ``ContractRisk``, a ``ValidationIssue``, or a
context assessment rule must be registered here. ``tests/test_risk_codes.py``
scans the source tree for code literals and fails on any emitted code that
is not registered; registering documented-but-not-yet-emitted or pending
codes is allowed (one-directional enforcement).

The risk tables under ``docs/modules/`` are explanatory references; this
module is the registry. Semantic changes to a code (meaning, severity, or
ownership) require joint confirmation by 路诚钺 (Chengyue-Lu) and 黄毅.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = [
    "ALIGNMENT_NOTE",
    "DOCUMENTED_GAP",
    "DYNAMIC_CODE_FAMILIES",
    "NOT_YET_EMITTED",
    "RISK_CODE_REGISTRY",
    "RiskCodeEntry",
]

# Applies to both DOCUMENTED_GAP and NOT_YET_EMITTED.
ALIGNMENT_NOTE = "语义对齐待路诚钺+黄毅共同确认"


@dataclass(frozen=True, slots=True)
class RiskCodeEntry:
    code: str
    severity: str  # as emitted: ContractRisk level (info/warning/block/human),
    # ValidationIssue severity (error/warning), or context assessment level
    # (warn/rollover/block); "a/b" when emission sites differ
    modules: tuple[str, ...]  # emitting modules, dotted paths
    summary: str  # one-line meaning
    docs: tuple[str, ...] = ()  # module doc tables listing the code
    status: str = "emitted"  # emitted | pending | not_yet_emitted


_CLI = "research_workbench.cli"
_CAPABILITY = "research_workbench.capability.resolver"
_CONTEXT = "research_workbench.context.models"
_HANDOFF_TRANSFER = "research_workbench.context.handoff_transfer"
_EVALUATION = "research_workbench.evaluation.skill_evaluation"
_OBSERVABILITY = "research_workbench.observability.models"
_VALIDATION_DOCS = "research_workbench.validation.documents"
_VALIDATION_RELS = "research_workbench.validation.relationships"

_DOC_04 = "docs/modules/04-SKILL_SYSTEM.md §10"
_DOC_05 = "docs/modules/05-TASK_AND_HANDOFF.md §8"
_DOC_06 = "docs/modules/06-CONTEXT_GOVERNANCE.md §8"
_DOC_08 = "docs/modules/08-VALIDATION_RISK_AND_GATES.md §4"

RISK_CODE_REGISTRY: tuple[RiskCodeEntry, ...] = (
    # research_workbench.cli
    RiskCodeEntry("HANDOFF-ASSIGNMENT-REF-DRIFT", "block", (_CLI,), "supplied Assignment differs from the Handoff Assignment reference"),
    RiskCodeEntry("HANDOFF-RECEIPT-BACKREF", "block", (_CLI,), "Execution Receipt does not list the Handoff as an output"),
    RiskCodeEntry("HANDOFF-RECEIPT-DRIFT", "block", (_CLI,), "Execution Receipt task or status differs from the Handoff"),
    RiskCodeEntry("HANDOFF-RECEIPT-MISSING", "block", (_CLI,), "Execution Receipt referenced by the Handoff does not exist"),
    RiskCodeEntry("REF-MISSING", "block", (_CLI, _OBSERVABILITY, _VALIDATION_RELS), "referenced file is missing or does not resolve within the project"),
    RiskCodeEntry("REF-OUTSIDE-ROOT", "block", (_CLI, _VALIDATION_RELS), "file reference escapes the project root"),
    RiskCodeEntry("RESUME-CONFLICT-GIT", "block", (_CLI,), "Main State Git baseline differs from the current HEAD", (_DOC_08,)),
    RiskCodeEntry("RESUME-GIT-UNAVAILABLE", "block", (_CLI,), "Main State pins a Git HEAD that the current project cannot resolve"),
    RiskCodeEntry("SKILL-PACKAGE-DRIFT", "block", (_CLI,), "Skill package content hash differs from the Assignment lock"),
    RiskCodeEntry("STATE-CONSTRAINT-LOSS", "block", (_CLI,), "checkpoint dropped pinned constraints"),
    RiskCodeEntry("STATE-CONTEXT-BLOCKED", "block", (_CLI,), "blocking context condition was not repaired before resume"),
    RiskCodeEntry("STATE-CONTEXT-SCOPE", "block", (_CLI,), "Main State must reference a main-scope Context Snapshot"),
    RiskCodeEntry("STATE-CONTEXT-SNAPSHOT-MISSING", "block", (_CLI,), "resume requires the pre-rollover Context Snapshot"),
    RiskCodeEntry("STATE-DECISION-LOSS", "block", (_CLI,), "checkpoint dropped accepted decisions"),
    RiskCodeEntry("STATE-DIGEST-MISSING", "block", (_CLI,), "Main State lacks the canonical checkpoint digest required for resume"),
    RiskCodeEntry("STATE-HANDOFF-EXPECTED", "block", (_CLI,), "active Task has no expected_handoff at checkpoint"),
    RiskCodeEntry("STATE-NEXT-ACTION-MISSING", "block", (_CLI,), "resume requires at least one bounded next action"),
    RiskCodeEntry("STATE-PROTOCOL-DRIFT", "block", (_CLI,), "Main State pins a Project Protocol different from the current one"),
    RiskCodeEntry("STATE-QUESTION-DRIFT", "block", (_CLI,), "Main State questions differ from the pinned Project Protocol"),
    RiskCodeEntry("STATE-ROLLOVER-REASON-MISSING", "block", (_CLI,), "pressure-triggered checkpoint does not explain its rollover reason"),
    RiskCodeEntry("STATE-SAFE-PAUSE-REASON-MISSING", "block", (_CLI,), "safe-paused Main State does not explain why work stopped"),
    # research_workbench.capability.resolver
    RiskCodeEntry("SKILL-AMBIGUOUS", "block", (_CAPABILITY,), "equivalent accepted Skill sets require an explicit human choice"),
    RiskCodeEntry("SKILL-CONFLICT", "block/error", (_CAPABILITY, _VALIDATION_DOCS), "Skills or their output contracts conflict", (_DOC_04, _DOC_08)),
    RiskCodeEntry("SKILL-FORBIDDEN", "block", (_CAPABILITY,), "forbidden Skills are loaded"),
    RiskCodeEntry("SKILL-IMPLICIT-CRITICAL", "block", (_CAPABILITY,), "critical Task does not explicitly name Skills", (_DOC_04,)),
    RiskCodeEntry("SKILL-MISSING", "block", (_CAPABILITY,), "required Skills are missing from the accepted Registry", (_DOC_04,)),
    RiskCodeEntry("SKILL-MODE-MISMATCH", "block", (_CAPABILITY,), "Skill applies to none of the active modes"),
    RiskCodeEntry("SKILL-TOOL-GAP", "block", (_CAPABILITY,), "Agent Profile does not allow the required tool capabilities"),
    RiskCodeEntry("TASK-DELEGATION-ESCALATION", "block", (_CAPABILITY,), "Task allows delegation but the Agent Profile forbids it"),
    RiskCodeEntry("TASK-OUTPUT-GAP", "block", (_CAPABILITY,), "required output contracts are not covered"),
    RiskCodeEntry("TASK-PERMISSION-ESCALATION", "block", (_CAPABILITY,), "Task requires permissions beyond the effective policy"),
    RiskCodeEntry("TASK-PROFILE-MISMATCH", "block", (_CAPABILITY,), "Task requests an Agent Profile different from the loaded one"),
    RiskCodeEntry("TASK-SKILL-MISMATCH", "block", (_CAPABILITY,), "required capabilities are not covered by Skills", (_DOC_05,)),
    # research_workbench.context.handoff_transfer
    RiskCodeEntry("HANDOFF-AUDIT-CONTRACT", "block", (_HANDOFF_TRANSFER,), "Transfer Audit input is invalid"),
    RiskCodeEntry("HANDOFF-AUDIT-COVERAGE", "block", (_HANDOFF_TRANSFER,), "Transfer Manifest items have no Handoff mapping", (_DOC_05, _DOC_08)),
    RiskCodeEntry("HANDOFF-AUDIT-DOCUMENT-INVALID", "block", (_HANDOFF_TRANSFER,), "linked document is not a valid instance of its kind"),
    RiskCodeEntry("HANDOFF-AUDIT-IDENTITY-DRIFT", "block", (_HANDOFF_TRANSFER,), "Transfer Manifest, Task, and Handoff identify different work"),
    RiskCodeEntry("HANDOFF-AUDIT-ITEM-DUPLICATE", "block", (_HANDOFF_TRANSFER,), "Transfer Manifest contains a duplicate item_id"),
    RiskCodeEntry("HANDOFF-AUDIT-LOCATOR-INVALID", "block", (_HANDOFF_TRANSFER,), "invalid Handoff JSON Pointer locator"),
    RiskCodeEntry("HANDOFF-AUDIT-MANIFEST-DRIFT", "block", (_HANDOFF_TRANSFER,), "Handoff does not point to the audited Transfer Manifest"),
    RiskCodeEntry("HANDOFF-AUDIT-MAPPING-DUPLICATE", "block", (_HANDOFF_TRANSFER,), "duplicate Transfer Manifest mapping"),
    RiskCodeEntry("HANDOFF-AUDIT-MAPPING-UNKNOWN", "block", (_HANDOFF_TRANSFER,), "mapping references an unknown Transfer Manifest item"),
    RiskCodeEntry("HANDOFF-AUDIT-REF-HASH", "block", (_HANDOFF_TRANSFER,), "audited reference content hash mismatch"),
    RiskCodeEntry("HANDOFF-AUDIT-REF-INVALID", "block", (_HANDOFF_TRANSFER,), "invalid file reference in the audited chain"),
    RiskCodeEntry("HANDOFF-AUDIT-REF-MISSING", "block", (_HANDOFF_TRANSFER,), "audited reference points to a missing file"),
    RiskCodeEntry("HANDOFF-AUDIT-REF-OUTSIDE", "block", (_HANDOFF_TRANSFER,), "audited reference escapes the project root"),
    RiskCodeEntry("HANDOFF-AUDIT-REQUIRED-OMITTED", "block", (_HANDOFF_TRANSFER,), "required Transfer Manifest item was omitted from the Handoff"),
    RiskCodeEntry("HANDOFF-AUDIT-SECTION-DRIFT", "block", (_HANDOFF_TRANSFER,), "Manifest item maps to an incompatible Handoff section"),
    RiskCodeEntry("HANDOFF-AUDIT-SOURCE-LOCATOR-INVALID", "block", (_HANDOFF_TRANSFER,), "item source locator does not resolve"),
    RiskCodeEntry("HANDOFF-AUDIT-SOURCE-NOT-INDEXED", "block", (_HANDOFF_TRANSFER,), "source artifact is absent from the Handoff artifact references"),
    RiskCodeEntry("HANDOFF-AUDIT-SOURCE-UNDECLARED", "block", (_HANDOFF_TRANSFER,), "item source_ref is not frozen in source_artifact_refs"),
    RiskCodeEntry("HANDOFF-NEGATIVE-UNMAPPED", "block", (_HANDOFF_TRANSFER,), "limitations, conflicts, open items, or human decisions lack source mappings", (_DOC_05, _DOC_08)),
    RiskCodeEntry("HANDOFF-REVIEW-CRITICAL-MISSING", "block", (_HANDOFF_TRANSFER,), "critical items were not reviewed"),
    RiskCodeEntry("HANDOFF-REVIEW-FINDING-COVERAGE", "block", (_HANDOFF_TRANSFER,), "review findings do not match the sampled item IDs"),
    RiskCodeEntry("HANDOFF-REVIEW-FINDING-DUPLICATE", "block", (_HANDOFF_TRANSFER,), "review findings contain duplicate item IDs"),
    RiskCodeEntry("HANDOFF-REVIEW-NOT-HUMAN", "block", (_HANDOFF_TRANSFER,), "model-only review cannot establish semantic preservation"),
    RiskCodeEntry("HANDOFF-REVIEW-NOT-INDEPENDENT", "block", (_HANDOFF_TRANSFER,), "reviewer is not independent of Handoff production"),
    RiskCodeEntry("HANDOFF-REVIEW-RISK-KIND-MISSING", "block", (_HANDOFF_TRANSFER,), "no item of a required risk kind was sampled"),
    RiskCodeEntry("HANDOFF-REVIEW-SAMPLE-DUPLICATE", "block", (_HANDOFF_TRANSFER,), "sampled review item IDs are not unique"),
    RiskCodeEntry("HANDOFF-REVIEW-SAMPLE-SMALL", "block", (_HANDOFF_TRANSFER,), "semantic sample is below the Task minimum"),
    RiskCodeEntry("HANDOFF-REVIEW-SAMPLE-UNKNOWN", "block", (_HANDOFF_TRANSFER,), "review sampled non-carried items"),
    RiskCodeEntry("HANDOFF-SEMANTIC-REVIEW-REQUIRED", "block", (_HANDOFF_TRANSFER,), "Task policy or transfer risk requires a bounded independent human review", (_DOC_08,)),
    RiskCodeEntry("HANDOFF-SEMANTIC-UNREVIEWED", "warning", (_HANDOFF_TRANSFER,), "structural coverage passed without a semantic-equivalence claim"),
    RiskCodeEntry("HANDOFF-SUMMARY-DISTORTION", "block", (_HANDOFF_TRANSFER,), "semantic review found the Handoff distorts its sources", (_DOC_05, _DOC_08)),
    # research_workbench.context.models
    RiskCodeEntry("CTX-AUTO-COMPACTION", "rollover", (_CONTEXT,), "unplanned compaction happened in the main context", (_DOC_06, _DOC_08)),
    RiskCodeEntry("CTX-CLOSEOUT-RESERVE-INSUFFICIENT", "block", (_CONTEXT,), "remaining budget cannot cover the minimal closeout reserve", (_DOC_08,)),
    RiskCodeEntry("CTX-HANDOFF-LOSS", "block", (_CONTEXT,), "subagent key information was not persisted before compaction", (_DOC_06, _DOC_08)),
    RiskCodeEntry("CTX-HIDDEN-STATE", "block", (_CONTEXT,), "a decision exists only in conversation or implicit state", (_DOC_06, _DOC_08)),
    RiskCodeEntry("CTX-MAIN-RAW-MATERIAL", "block", (_CONTEXT,), "raw material sits in main context where policy forbids it"),
    RiskCodeEntry("CTX-MAIN-RAW-MATERIAL-ON-DEMAND", "warn", (_CONTEXT,), "raw material stays in main context beyond its bounded dispute"),
    RiskCodeEntry("CTX-METRICS-UNKNOWN", "warn", (_CONTEXT,), "pressure metrics are unavailable; cost conclusions are forbidden", (_DOC_08,)),
    RiskCodeEntry("CTX-NEXT-AWU-COST-UNKNOWN", "warn", (_CONTEXT,), "next atomic work unit cost cannot be inferred from percentages alone"),
    RiskCodeEntry("CTX-NEXT-AWU-UNSAFE", "rollover", (_CONTEXT,), "remaining budget cannot cover the next atomic work unit plus closeout", (_DOC_08,)),
    RiskCodeEntry("CTX-SUBAGENT-COMPACTION-RECOVERABLE", "warn", (_CONTEXT,), "subagent session compacted with a persisted Handoff ready"),
    # research_workbench.evaluation.skill_evaluation
    RiskCodeEntry("EVAL-ASSIGNMENT-DRIFT", "block", (_EVALUATION,), "paired Skill Assignments differ beyond the candidate"),
    RiskCodeEntry("EVAL-ASSIGNMENT-INVALID", "block", (_EVALUATION,), "invalid Skill Assignment"),
    RiskCodeEntry("EVAL-ASSIGNMENT-MISSING", "block", (_EVALUATION,), "missing Skill Assignment"),
    RiskCodeEntry("EVAL-ASSIGNMENT-TASK-DRIFT", "block", (_EVALUATION,), "Skill Assignment belongs to a different Task"),
    RiskCodeEntry("EVAL-BASE-CONTEXT-DRIFT", "block", (_EVALUATION,), "paired arms loaded different non-Skill context volumes"),
    RiskCodeEntry("EVAL-BASELINE-CANDIDATE-LOADED", "block", (_EVALUATION,), "baseline Skill Assignment contains the candidate"),
    RiskCodeEntry("EVAL-BASELINE-CONTAMINATED", "block", (_EVALUATION,), "baseline arm loaded Skill instructions"),
    RiskCodeEntry("EVAL-CANDIDATE-ASSIGNMENT-DRIFT", "block", (_EVALUATION,), "candidate Skill lock differs between arms"),
    RiskCodeEntry("EVAL-CANDIDATE-ASSIGNMENT-MISSING", "block", (_EVALUATION,), "with-Skill Assignment must contain exactly one candidate lock"),
    RiskCodeEntry("EVAL-CANDIDATE-PIN-DRIFT", "block", (_EVALUATION,), "candidate Registry differs from the frozen pin"),
    RiskCodeEntry("EVAL-CANDIDATE-REGISTRY-INVALID", "block", (_EVALUATION,), "candidate Registry cannot be loaded"),
    RiskCodeEntry("EVAL-CANDIDATE-REGISTRY-MISSING", "block", (_EVALUATION,), "candidate Registry is missing"),
    RiskCodeEntry("EVAL-CANDIDATE-UNPINNED", "block", (_EVALUATION,), "candidate is not uniquely registered"),
    RiskCodeEntry("EVAL-CASE-COVERAGE", "block", (_EVALUATION,), "missing required evaluation case kinds"),
    RiskCodeEntry("EVAL-CASE-DUPLICATE", "block", (_EVALUATION,), "duplicate case_id"),
    RiskCodeEntry("EVAL-CHECKER-DRIFT", "block", (_EVALUATION,), "paired arms used different deterministic checkers"),
    RiskCodeEntry("EVAL-CONTEXT-DRIFT", "block", (_EVALUATION,), "arm context differs from the Context Snapshot"),
    RiskCodeEntry("EVAL-CONTEXT-INCONSISTENT", "block", (_EVALUATION,), "loaded character totals are inconsistent with task plus Skill characters"),
    RiskCodeEntry("EVAL-CONTEXT-INVALID", "block", (_EVALUATION,), "invalid Context Snapshot"),
    RiskCodeEntry("EVAL-CONTEXT-NOT-RUNTIME", "block", (_EVALUATION,), "Context Snapshot is not runtime-measured"),
    RiskCodeEntry("EVAL-CONTEXT-RECEIPT-MISSING", "block", (_EVALUATION,), "receipt has no Context Snapshot"),
    RiskCodeEntry("EVAL-CONTEXT-UNMEASURED", "block", (_EVALUATION,), "live paired context must be measured"),
    RiskCodeEntry("EVAL-DECISION-DRIFT", "block", (_EVALUATION,), "Decision metadata differs from the evaluation"),
    RiskCodeEntry("EVAL-DECISION-INVALID", "block", (_EVALUATION,), "admission decision is not a valid Decision object"),
    RiskCodeEntry("EVAL-DECISION-MISSING", "block", (_EVALUATION,), "human-decided evaluation lacks a live Decision file"),
    RiskCodeEntry("EVAL-FIXTURE-ONLY", "block", (_EVALUATION,), "fixture-only evidence cannot support Skill admission"),
    RiskCodeEntry("EVAL-HUMAN-REVIEW-MISSING", "block", (_EVALUATION,), "review has no human reviewer"),
    RiskCodeEntry("EVAL-INPUT-DRIFT", "block", (_EVALUATION,), "paired arms report different input sizes"),
    RiskCodeEntry("EVAL-INPUT-MEASUREMENT-DRIFT", "block", (_EVALUATION,), "recorded task input characters differ from frozen files"),
    RiskCodeEntry("EVAL-LIVE-CASE-COUNT", "block", (_EVALUATION,), "live case count is below the required minimum"),
    RiskCodeEntry("EVAL-MODEL-CONFIG-DRIFT", "block", (_EVALUATION,), "model configuration hashes differ between arms"),
    RiskCodeEntry("EVAL-MODEL-CONFIG-UNPINNED", "block", (_EVALUATION,), "model configuration hash differs from the frozen artifact"),
    RiskCodeEntry("EVAL-MODEL-DRIFT", "block", (_EVALUATION,), "paired arms declare different provider/models"),
    RiskCodeEntry("EVAL-MODEL-IDENTITY-MISSING", "block", (_EVALUATION,), "paired arms must identify provider and model"),
    RiskCodeEntry("EVAL-MODEL-RECEIPT-DRIFT", "block", (_EVALUATION,), "receipt differs from the arm model identity"),
    RiskCodeEntry("EVAL-NO-OBSERVED-GAIN", "warning", (_EVALUATION,), "with-Skill scores do not improve any recorded criterion"),
    RiskCodeEntry("EVAL-PROFILE-ASSIGNMENT-DRIFT", "block", (_EVALUATION,), "Agent Profile differs from the Skill Assignment"),
    RiskCodeEntry("EVAL-PROFILE-DRIFT", "block", (_EVALUATION,), "paired arms used different Agent Profiles"),
    RiskCodeEntry("EVAL-PROFILE-INVALID", "block", (_EVALUATION,), "invalid Agent Profile"),
    RiskCodeEntry("EVAL-PROFILE-MISSING", "block", (_EVALUATION,), "missing Agent Profile"),
    RiskCodeEntry("EVAL-PROJECT-PROTOCOL-INVALID", "block", (_EVALUATION,), "Project Protocol fails its Schema or contract"),
    RiskCodeEntry("EVAL-PROJECT-PROTOCOL-MISSING", "block", (_EVALUATION,), "live evaluation has no Project Protocol"),
    RiskCodeEntry("EVAL-RECEIPT-INCOMPLETE", "block", (_EVALUATION,), "execution status is not completed"),
    RiskCodeEntry("EVAL-RECEIPT-INVALID", "block", (_EVALUATION,), "Execution Receipt is not a valid object"),
    RiskCodeEntry("EVAL-RECEIPT-LINKAGE-INVALID", "block", (_EVALUATION,), "linked execution evidence is invalid"),
    RiskCodeEntry("EVAL-RECEIPT-MISSING", "block", (_EVALUATION,), "Execution Receipt is required or missing"),
    RiskCodeEntry("EVAL-RECEIPT-NOT-LIVE", "block", (_EVALUATION,), "execution is not a live model run"),
    RiskCodeEntry("EVAL-RECEIPT-OUTPUT-DRIFT", "block", (_EVALUATION,), "receipt omits the paired output"),
    RiskCodeEntry("EVAL-RECEIPT-VALIDATION-DRIFT", "block", (_EVALUATION,), "receipt omits the paired validation report"),
    RiskCodeEntry("EVAL-REF-HASH", "block", (_EVALUATION,), "evaluation reference content hash mismatch"),
    RiskCodeEntry("EVAL-REF-INVALID", "block", (_EVALUATION,), "invalid file reference in evaluation evidence"),
    RiskCodeEntry("EVAL-REF-MISSING", "block", (_EVALUATION,), "evaluation reference points to a missing file"),
    RiskCodeEntry("EVAL-REF-OUTSIDE", "block", (_EVALUATION,), "evaluation reference escapes the project root"),
    RiskCodeEntry("EVAL-REVIEW-CRITERIA", "block", (_EVALUATION,), "missing review criteria"),
    RiskCodeEntry("EVAL-REVIEW-CRITERIA-DUPLICATE", "block", (_EVALUATION,), "duplicate review criterion IDs"),
    RiskCodeEntry("EVAL-REVIEW-NOT-INDEPENDENT", "block", (_EVALUATION,), "reviewer is not independent"),
    RiskCodeEntry("EVAL-REVIEW-PENDING", "block", (_EVALUATION,), "live case has no completed blind review"),
    RiskCodeEntry("EVAL-REVIEW-TIME-DRIFT", "block", (_EVALUATION,), "condition reveal precedes scoring"),
    RiskCodeEntry("EVAL-REVIEW-UNBLINDED", "block", (_EVALUATION,), "condition order was exposed before scoring"),
    RiskCodeEntry("EVAL-RUNTIME-DRIFT", "block", (_EVALUATION,), "paired arms used different runtimes"),
    RiskCodeEntry("EVAL-SKILL-NOT-LOADED", "block", (_EVALUATION,), "with-Skill arm loaded no instructions"),
    RiskCodeEntry("EVAL-SKILL-PACKAGE-DRIFT", "block", (_EVALUATION,), "Skill package hash does not match live files"),
    RiskCodeEntry("EVAL-STATUS-OVERCLAIM", "block", (_EVALUATION,), "evaluation declares admission eligibility despite blocking evidence gaps"),
    RiskCodeEntry("EVAL-TASK-DRIFT", "block", (_EVALUATION,), "paired receipts identify different Tasks"),
    RiskCodeEntry("EVAL-TIME-UNMEASURED", "block", (_EVALUATION,), "execution wall time is unavailable"),
    RiskCodeEntry("EVAL-USAGE-NOT-MEASURED", "warning", (_EVALUATION,), "token/cost usage unmeasured; savings cannot be claimed"),
    RiskCodeEntry("EVAL-USAGE-STATUS-DRIFT", "block", (_EVALUATION,), "paired usage status differs"),
    RiskCodeEntry("EVAL-USAGE-UNCOMPARABLE", "block", (_EVALUATION,), "live model execution cannot use not-applicable usage"),
    RiskCodeEntry("EVAL-VALIDATION-INVALID", "block", (_EVALUATION,), "validation evidence is not a deterministic check report"),
    RiskCodeEntry("EVAL-VALIDATION-STATUS-DRIFT", "block", (_EVALUATION,), "arm status differs from the validation report"),
    RiskCodeEntry("EVAL-VALIDATION-SUBJECT-DRIFT", "block", (_EVALUATION,), "validation report omits required subjects"),
    RiskCodeEntry("EVAL-WITH-SKILL-CHECK", "block", (_EVALUATION,), "with-Skill deterministic status is not pass"),
    # research_workbench.observability.models
    RiskCodeEntry("COORDINATION-COST-HIGH", "warning", (_OBSERVABILITY,), "coordination ratio exceeds the Project Protocol budget", (_DOC_08,)),
    RiskCodeEntry("COORDINATION-COST-UNKNOWN", "warning", (_OBSERVABILITY,), "execution lacks token- or time-based coordination measurements"),
    RiskCodeEntry("COST-USAGE-UNKNOWN", "warning", (_OBSERVABILITY,), "model usage is unavailable; token or cost savings cannot be claimed", (_DOC_08,)),
    RiskCodeEntry("DELEGATION-FANOUT", "block", (_OBSERVABILITY,), "observed parallel delegation exceeds the Project Protocol budget", (_DOC_08,)),
    RiskCodeEntry("RECEIPT-ASSIGNMENT-MISMATCH", "block", (_OBSERVABILITY,), "Execution Receipt task identity does not match the Skill Assignment"),
    RiskCodeEntry("RECEIPT-ATTEMPT-ASSIGNMENT-MISMATCH", "block", (_OBSERVABILITY,), "Attempt and Execution Receipt point to different Skill Assignments"),
    RiskCodeEntry("RECEIPT-ATTEMPT-BACKREF", "block", (_OBSERVABILITY,), "Attempt does not point back to the Execution Receipt"),
    RiskCodeEntry("RECEIPT-ATTEMPT-OUTPUT-LOSS", "block", (_OBSERVABILITY,), "Execution Receipt omits Attempt outputs"),
    RiskCodeEntry("RECEIPT-CONTEXT-BLOCKED", "block", (_OBSERVABILITY,), "Context Snapshot contains an unresolved blocking condition"),
    RiskCodeEntry("RECEIPT-CONTEXT-OWNER-MISMATCH", "block", (_OBSERVABILITY,), "task Context Snapshot belongs to a different owner"),
    RiskCodeEntry("RECEIPT-HANDOFF-BACKREF", "block", (_OBSERVABILITY,), "Handoff output does not point back to the Execution Receipt"),
    RiskCodeEntry("RECEIPT-HANDOFF-TASK-MISMATCH", "block", (_OBSERVABILITY,), "Handoff output belongs to a different Task"),
    RiskCodeEntry("RECEIPT-MACHINE-VALIDATION-MISSING", "block", (_OBSERVABILITY,), "completion requires at least one understood machine validation artifact"),
    RiskCodeEntry("RECEIPT-MISSING-OUTPUT", "block", (_OBSERVABILITY,), "completed execution has no output references"),
    RiskCodeEntry("RECEIPT-PROFILE-MISMATCH", "block", (_OBSERVABILITY,), "Agent Profile does not match the Skill Assignment"),
    RiskCodeEntry("RECEIPT-RUNTIME-SNAPSHOT-MISMATCH", "block", (_OBSERVABILITY,), "Attempt and Execution Receipt point to different Runtime snapshots"),
    RiskCodeEntry("RECEIPT-SAFE-PAUSE-CONTEXT-MISSING", "block", (_OBSERVABILITY,), "safe-paused execution must pin the triggering Context Snapshot"),
    RiskCodeEntry("RECEIPT-SAFE-PAUSE-HANDOFF-MISSING", "block", (_OBSERVABILITY,), "safe-paused execution must persist a recoverable Handoff"),
    RiskCodeEntry("RECEIPT-STATUS-MISMATCH", "block", (_OBSERVABILITY,), "Execution Receipt status does not match the Attempt"),
    RiskCodeEntry("RECEIPT-TASK-MISMATCH", "block", (_OBSERVABILITY,), "Execution Receipt task identity does not match the Attempt"),
    RiskCodeEntry("RECEIPT-TIME-MISMATCH", "block", (_OBSERVABILITY,), "Execution Receipt timestamps do not match the Attempt"),
    RiskCodeEntry("RECEIPT-VALIDATION-FAILED", "block", (_OBSERVABILITY,), "referenced machine validation failed", (_DOC_08,)),
    RiskCodeEntry("RECEIPT-VALIDATION-INVALID", "block", (_OBSERVABILITY,), "referenced validation report is schema-invalid"),
    RiskCodeEntry("RECEIPT-VALIDATION-SCOPE-MISMATCH", "block", (_OBSERVABILITY,), "validation report does not pin an Attempt or output from this Receipt"),
    RiskCodeEntry("REVIEW-LOOP", "warning", (_OBSERVABILITY,), "more than one review round requires an explicit benefit justification", (_DOC_08,)),
    RiskCodeEntry("TRACE-DATA-BOUNDARY", "block", (_OBSERVABILITY,), "external trace conflicts with the local-only Project Protocol", (_DOC_08,)),
    RiskCodeEntry("TRACE-OVERRETENTION", "warning", (_OBSERVABILITY,), "full trace retention exceeds the current diagnostic need"),
    RiskCodeEntry("TRACE-SENSITIVE", "block", (_OBSERVABILITY,), "trace reports sensitive data that must be redacted or deleted", (_DOC_08,)),
    # research_workbench.validation.documents
    RiskCodeEntry("ACCEPTED-DUPLICATE", "error", (_VALIDATION_DOCS,), "duplicate accepted Skill"),
    RiskCodeEntry("ACCEPTED-INVALID", "error", (_VALIDATION_DOCS,), "accepted Skill entry is not an object"),
    RiskCodeEntry("ACCEPTED-STATUS", "error", (_VALIDATION_DOCS,), "accepted entry is not marked accepted"),
    RiskCodeEntry("CANDIDATE-DUPLICATE", "error", (_VALIDATION_DOCS,), "duplicate candidate_id in the Skill Registry"),
    RiskCodeEntry("CANDIDATE-INVALID", "error", (_VALIDATION_DOCS,), "Skill Registry candidate entry is not an object"),
    RiskCodeEntry("CANDIDATE-STATUS", "error", (_VALIDATION_DOCS,), "invalid candidate status in the Skill Registry"),
    RiskCodeEntry("CANDIDATE-UNPINNED", "error", (_VALIDATION_DOCS,), "accepted candidate lacks a content_hash"),
    RiskCodeEntry("DOCUMENT-INVALID", "error", (_VALIDATION_DOCS,), "top-level document value must be an object"),
    RiskCodeEntry("DOCUMENT-UNKNOWN", "error", (_VALIDATION_DOCS,), "document kind cannot be inferred"),
    RiskCodeEntry("FIELD-MISSING", "error", (_VALIDATION_DOCS,), "required field is missing"),
    RiskCodeEntry("HASH-INVALID", "error", (_VALIDATION_DOCS,), "content hash is not 64 hexadecimal characters"),
    RiskCodeEntry("HASH-PLACEHOLDER", "warning", (_VALIDATION_DOCS,), "content hash is still a placeholder"),
    RiskCodeEntry("MODEL-POOL-INVALID", "error", (_VALIDATION_DOCS,), "model pool contract error"),
    RiskCodeEntry("PARSE-ERROR", "error", (_VALIDATION_DOCS,), "document cannot be parsed"),
    RiskCodeEntry("PROVIDER-ADAPTER-DUPLICATE", "error", (_VALIDATION_DOCS,), "duplicate adapter_id"),
    RiskCodeEntry("PROVIDER-ADAPTER-INVALID", "error", (_VALIDATION_DOCS,), "provider adapter entry is not an object"),
    RiskCodeEntry("SCHEMA-INVALID", "error", (_VALIDATION_DOCS,), "document fails its JSON Schema"),
    RiskCodeEntry("SCOPE-ABSOLUTE", "error", (_VALIDATION_DOCS,), "write_scope must be repository-relative"),
    RiskCodeEntry("SOURCE-DUPLICATE", "error", (_VALIDATION_DOCS,), "duplicate source_id in the Skill Registry"),
    RiskCodeEntry("SOURCE-INVALID", "error", (_VALIDATION_DOCS,), "Skill Registry source entry is not an object"),
    RiskCodeEntry("SOURCE-UNKNOWN", "error", (_VALIDATION_DOCS,), "candidate references an unknown source"),
    # research_workbench.validation.relationships
    RiskCodeEntry("CLAIM-OVERREACH", "block", (_VALIDATION_RELS,), "claim strength is outside the project ceiling", (_DOC_08,)),
    RiskCodeEntry("HANDOFF-ASSIGNMENT-MISSING", "block", (_VALIDATION_RELS,), "controlled Handoff does not retain its Skill Assignment reference"),
    RiskCodeEntry("HANDOFF-ASSIGNMENT-PROFILE-DRIFT", "block", (_VALIDATION_RELS,), "Skill Assignment Agent Profile does not match the Task"),
    RiskCodeEntry("HANDOFF-ASSIGNMENT-SKILL-DRIFT", "block", (_VALIDATION_RELS,), "Handoff Skill locks differ from the Assignment"),
    RiskCodeEntry("HANDOFF-ASSIGNMENT-TASK-DRIFT", "block", (_VALIDATION_RELS,), "Skill Assignment does not match the Task identity or revision"),
    RiskCodeEntry("HANDOFF-MISSING-OUTPUT", "block", (_VALIDATION_RELS,), "completed Handoff has no artifact references", (_DOC_05,)),
    RiskCodeEntry("HANDOFF-SAFE-PAUSE-NEXT-ACTION-MISSING", "block", (_VALIDATION_RELS,), "safe-paused Handoff must provide a bounded resume action"),
    RiskCodeEntry("HANDOFF-SAFE-PAUSE-STATE-MISSING", "block", (_VALIDATION_RELS,), "safe-paused Handoff must state unfinished work"),
    RiskCodeEntry("HANDOFF-SKILL-LOSS", "block", (_VALIDATION_RELS,), "Handoff does not lock the required Skills"),
    RiskCodeEntry("HANDOFF-TASK-MISMATCH", "block", (_VALIDATION_RELS,), "Handoff task does not match the Task identity"),
    RiskCodeEntry("HANDOFF-TRANSFER-MANIFEST-MISSING", "block", (_VALIDATION_RELS,), "Task requires a Transfer Manifest but the Handoff does not reference one"),
    RiskCodeEntry("HANDOFF-WAITING-DECISION-MISSING", "block", (_VALIDATION_RELS,), "waiting Handoff must identify the awaited human decision"),
    RiskCodeEntry("REF-HASH-MISMATCH", "block", (_VALIDATION_RELS,), "referenced file content hash differs from the lock"),
    RiskCodeEntry("TASK-STALE-INPUT", "block", (_VALIDATION_RELS,), "Handoff input lock differs from the Task input references", (_DOC_05,)),
    RiskCodeEntry("TASK-WRITE-OVERLAP", "block", (_VALIDATION_RELS,), "parallel Tasks have overlapping write scopes", (_DOC_05,)),
    # The registry admits status="pending" entries so a code can be referenced
    # before its emission lands; none are pending at the moment.
    RiskCodeEntry("RECEIPT-REF-INVALID", "block", (_OBSERVABILITY,), "Execution Receipt file reference is invalid"),
)

# Emitted codes that no module doc table registers yet. Alignment with the
# docs is pending: ALIGNMENT_NOTE.
DOCUMENTED_GAP: tuple[str, ...] = (
    "ACCEPTED-DUPLICATE",
    "ACCEPTED-INVALID",
    "ACCEPTED-STATUS",
    "CANDIDATE-DUPLICATE",
    "CANDIDATE-INVALID",
    "CANDIDATE-STATUS",
    "CANDIDATE-UNPINNED",
    "COORDINATION-COST-UNKNOWN",
    "CTX-MAIN-RAW-MATERIAL",
    "CTX-MAIN-RAW-MATERIAL-ON-DEMAND",
    "CTX-NEXT-AWU-COST-UNKNOWN",
    "CTX-SUBAGENT-COMPACTION-RECOVERABLE",
    "DOCUMENT-INVALID",
    "DOCUMENT-UNKNOWN",
    "EVAL-ASSIGNMENT-DRIFT",
    "EVAL-ASSIGNMENT-INVALID",
    "EVAL-ASSIGNMENT-MISSING",
    "EVAL-ASSIGNMENT-TASK-DRIFT",
    "EVAL-BASE-CONTEXT-DRIFT",
    "EVAL-BASELINE-CANDIDATE-LOADED",
    "EVAL-BASELINE-CONTAMINATED",
    "EVAL-CANDIDATE-ASSIGNMENT-DRIFT",
    "EVAL-CANDIDATE-ASSIGNMENT-MISSING",
    "EVAL-CANDIDATE-PIN-DRIFT",
    "EVAL-CANDIDATE-REGISTRY-INVALID",
    "EVAL-CANDIDATE-REGISTRY-MISSING",
    "EVAL-CANDIDATE-UNPINNED",
    "EVAL-CASE-COVERAGE",
    "EVAL-CASE-DUPLICATE",
    "EVAL-CHECKER-DRIFT",
    "EVAL-CONTEXT-DRIFT",
    "EVAL-CONTEXT-INCONSISTENT",
    "EVAL-CONTEXT-INVALID",
    "EVAL-CONTEXT-NOT-RUNTIME",
    "EVAL-CONTEXT-RECEIPT-MISSING",
    "EVAL-CONTEXT-UNMEASURED",
    "EVAL-DECISION-DRIFT",
    "EVAL-DECISION-INVALID",
    "EVAL-DECISION-MISSING",
    "EVAL-FIXTURE-ONLY",
    "EVAL-HUMAN-REVIEW-MISSING",
    "EVAL-INPUT-DRIFT",
    "EVAL-INPUT-MEASUREMENT-DRIFT",
    "EVAL-LIVE-CASE-COUNT",
    "EVAL-MODEL-CONFIG-DRIFT",
    "EVAL-MODEL-CONFIG-UNPINNED",
    "EVAL-MODEL-DRIFT",
    "EVAL-MODEL-IDENTITY-MISSING",
    "EVAL-MODEL-RECEIPT-DRIFT",
    "EVAL-NO-OBSERVED-GAIN",
    "EVAL-PROFILE-ASSIGNMENT-DRIFT",
    "EVAL-PROFILE-DRIFT",
    "EVAL-PROFILE-INVALID",
    "EVAL-PROFILE-MISSING",
    "EVAL-PROJECT-PROTOCOL-INVALID",
    "EVAL-PROJECT-PROTOCOL-MISSING",
    "EVAL-RECEIPT-INCOMPLETE",
    "EVAL-RECEIPT-INVALID",
    "EVAL-RECEIPT-LINKAGE-INVALID",
    "EVAL-RECEIPT-MISSING",
    "EVAL-RECEIPT-NOT-LIVE",
    "EVAL-RECEIPT-OUTPUT-DRIFT",
    "EVAL-RECEIPT-VALIDATION-DRIFT",
    "EVAL-REF-HASH",
    "EVAL-REF-INVALID",
    "EVAL-REF-MISSING",
    "EVAL-REF-OUTSIDE",
    "EVAL-REVIEW-CRITERIA",
    "EVAL-REVIEW-CRITERIA-DUPLICATE",
    "EVAL-REVIEW-NOT-INDEPENDENT",
    "EVAL-REVIEW-PENDING",
    "EVAL-REVIEW-TIME-DRIFT",
    "EVAL-REVIEW-UNBLINDED",
    "EVAL-RUNTIME-DRIFT",
    "EVAL-SKILL-NOT-LOADED",
    "EVAL-SKILL-PACKAGE-DRIFT",
    "EVAL-STATUS-OVERCLAIM",
    "EVAL-TASK-DRIFT",
    "EVAL-TIME-UNMEASURED",
    "EVAL-USAGE-NOT-MEASURED",
    "EVAL-USAGE-STATUS-DRIFT",
    "EVAL-USAGE-UNCOMPARABLE",
    "EVAL-VALIDATION-INVALID",
    "EVAL-VALIDATION-STATUS-DRIFT",
    "EVAL-VALIDATION-SUBJECT-DRIFT",
    "EVAL-WITH-SKILL-CHECK",
    "FIELD-MISSING",
    "HANDOFF-ASSIGNMENT-MISSING",
    "HANDOFF-ASSIGNMENT-PROFILE-DRIFT",
    "HANDOFF-ASSIGNMENT-REF-DRIFT",
    "HANDOFF-ASSIGNMENT-SKILL-DRIFT",
    "HANDOFF-ASSIGNMENT-TASK-DRIFT",
    "HANDOFF-AUDIT-CONTRACT",
    "HANDOFF-AUDIT-DOCUMENT-INVALID",
    "HANDOFF-AUDIT-IDENTITY-DRIFT",
    "HANDOFF-AUDIT-ITEM-DUPLICATE",
    "HANDOFF-AUDIT-LOCATOR-INVALID",
    "HANDOFF-AUDIT-MANIFEST-DRIFT",
    "HANDOFF-AUDIT-MAPPING-DUPLICATE",
    "HANDOFF-AUDIT-MAPPING-UNKNOWN",
    "HANDOFF-AUDIT-REF-HASH",
    "HANDOFF-AUDIT-REF-INVALID",
    "HANDOFF-AUDIT-REF-MISSING",
    "HANDOFF-AUDIT-REF-OUTSIDE",
    "HANDOFF-AUDIT-REQUIRED-OMITTED",
    "HANDOFF-AUDIT-SECTION-DRIFT",
    "HANDOFF-AUDIT-SOURCE-LOCATOR-INVALID",
    "HANDOFF-AUDIT-SOURCE-NOT-INDEXED",
    "HANDOFF-AUDIT-SOURCE-UNDECLARED",
    "HANDOFF-RECEIPT-BACKREF",
    "HANDOFF-RECEIPT-DRIFT",
    "HANDOFF-RECEIPT-MISSING",
    "HANDOFF-REVIEW-CRITICAL-MISSING",
    "HANDOFF-REVIEW-FINDING-COVERAGE",
    "HANDOFF-REVIEW-FINDING-DUPLICATE",
    "HANDOFF-REVIEW-NOT-HUMAN",
    "HANDOFF-REVIEW-NOT-INDEPENDENT",
    "HANDOFF-REVIEW-RISK-KIND-MISSING",
    "HANDOFF-REVIEW-SAMPLE-DUPLICATE",
    "HANDOFF-REVIEW-SAMPLE-SMALL",
    "HANDOFF-REVIEW-SAMPLE-UNKNOWN",
    "HANDOFF-SAFE-PAUSE-NEXT-ACTION-MISSING",
    "HANDOFF-SAFE-PAUSE-STATE-MISSING",
    "HANDOFF-SEMANTIC-UNREVIEWED",
    "HANDOFF-SKILL-LOSS",
    "HANDOFF-TASK-MISMATCH",
    "HANDOFF-TRANSFER-MANIFEST-MISSING",
    "HANDOFF-WAITING-DECISION-MISSING",
    "HASH-INVALID",
    "HASH-PLACEHOLDER",
    "MODEL-POOL-INVALID",
    "PARSE-ERROR",
    "PROVIDER-ADAPTER-DUPLICATE",
    "PROVIDER-ADAPTER-INVALID",
    "RECEIPT-ASSIGNMENT-MISMATCH",
    "RECEIPT-ATTEMPT-ASSIGNMENT-MISMATCH",
    "RECEIPT-ATTEMPT-BACKREF",
    "RECEIPT-ATTEMPT-OUTPUT-LOSS",
    "RECEIPT-CONTEXT-BLOCKED",
    "RECEIPT-CONTEXT-OWNER-MISMATCH",
    "RECEIPT-HANDOFF-BACKREF",
    "RECEIPT-HANDOFF-TASK-MISMATCH",
    "RECEIPT-MACHINE-VALIDATION-MISSING",
    "RECEIPT-MISSING-OUTPUT",
    "RECEIPT-PROFILE-MISMATCH",
    "RECEIPT-REF-INVALID",
    "RECEIPT-RUNTIME-SNAPSHOT-MISMATCH",
    "RECEIPT-SAFE-PAUSE-CONTEXT-MISSING",
    "RECEIPT-SAFE-PAUSE-HANDOFF-MISSING",
    "RECEIPT-STATUS-MISMATCH",
    "RECEIPT-TASK-MISMATCH",
    "RECEIPT-TIME-MISMATCH",
    "RECEIPT-VALIDATION-INVALID",
    "RECEIPT-VALIDATION-SCOPE-MISMATCH",
    "REF-HASH-MISMATCH",
    "REF-MISSING",
    "REF-OUTSIDE-ROOT",
    "RESUME-GIT-UNAVAILABLE",
    "SCHEMA-INVALID",
    "SCOPE-ABSOLUTE",
    "SKILL-AMBIGUOUS",
    "SKILL-FORBIDDEN",
    "SKILL-MODE-MISMATCH",
    "SKILL-PACKAGE-DRIFT",
    "SKILL-TOOL-GAP",
    "SOURCE-DUPLICATE",
    "SOURCE-INVALID",
    "SOURCE-UNKNOWN",
    "STATE-CONSTRAINT-LOSS",
    "STATE-CONTEXT-BLOCKED",
    "STATE-CONTEXT-SCOPE",
    "STATE-CONTEXT-SNAPSHOT-MISSING",
    "STATE-DECISION-LOSS",
    "STATE-DIGEST-MISSING",
    "STATE-HANDOFF-EXPECTED",
    "STATE-NEXT-ACTION-MISSING",
    "STATE-PROTOCOL-DRIFT",
    "STATE-QUESTION-DRIFT",
    "STATE-ROLLOVER-REASON-MISSING",
    "STATE-SAFE-PAUSE-REASON-MISSING",
    "TASK-DELEGATION-ESCALATION",
    "TASK-OUTPUT-GAP",
    "TASK-PERMISSION-ESCALATION",
    "TASK-PROFILE-MISMATCH",
    "TRACE-OVERRETENTION",
)

# Codes registered in module doc tables (04 §10, 05 §8, 06 §8) with zero
# emission sites. Severity is the doc-stated default where given. Alignment
# with the code is pending: ALIGNMENT_NOTE.
NOT_YET_EMITTED: tuple[RiskCodeEntry, ...] = (
    RiskCodeEntry("SKILL-VERSION-DRIFT", "block", (), "executed Skill version differs from the Assignment", (_DOC_04,), "not_yet_emitted"),
    RiskCodeEntry("SKILL-CONTEXT-FLOOD", "warn/block", (), "total Skill context exceeds the budget", (_DOC_04,), "not_yet_emitted"),
    RiskCodeEntry("SKILL-PERMISSION-ESCALATION", "block", (), "Skill requests permissions beyond the granted scope", (_DOC_04,), "not_yet_emitted"),
    RiskCodeEntry("SKILL-SUPPLY-CHAIN", "human", (), "Skill source, scripts, or license are unverified", (_DOC_04,), "not_yet_emitted"),
    RiskCodeEntry("SKILL-TAXONOMY-GROWTH", "warn", (), "Registry grows while actual reuse stays low", (_DOC_04,), "not_yet_emitted"),
    RiskCodeEntry("SKILL-STALE-EVAL", "warn", (), "no regression evaluation after a Skill version update", (_DOC_04,), "not_yet_emitted"),
    RiskCodeEntry("TASK-TOO-BROAD", "", (), "Task goal cannot be completed within budget", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("HANDOFF-LOSSY", "", (), "Handoff summary carries key conclusions without references", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("HANDOFF-OMITS-NEGATIVE", "", (), "failures, counter-evidence, or limitations are not handed off", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("HANDOFF-CLAIM-UPGRADE", "", (), "Handoff exceeds the Claim ceiling", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("HANDOFF-OVERHEAD", "", (), "audit artifact cost grows without changing accept, rework, or Gate decisions", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("TASK-READ-OUTSIDE-SCOPE", "", (), "Agent reads undeclared content without a Task scope-extension record", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("TRACE-MESSAGE-MISSING", "", (), "a cross-agent transmission has no matching message in the Attempt Archive", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("TRACE-ACTOR-UNOWNED", "", (), "an agent actor is not bound to a named accountable human", (_DOC_05,), "not_yet_emitted"),
    RiskCodeEntry("CTX-MAIN-PRESSURE", "", (), "main context noise is growing", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-SUMMARY-DISTORTION", "", (), "a summary changes the qualifying conditions of its source", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-STALE", "", (), "context references a stale revision", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-RECALL-LOOP", "", (), "main agent repeatedly re-reads raw material", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-PINNED-GROWTH", "", (), "pinned information only grows", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-SKILL-POLLUTION", "", (), "irrelevant Skills are loaded", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-RECOVERY-DRIFT", "", (), "goals changed after fresh-session recovery", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-READ-SCOPE-DRIFT", "", (), "Agent reads undeclared content or treats transient material as formal input", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-HANDOFF-OVERHEAD", "", (), "Handoff artifacts grow without changing decisions", (_DOC_06,), "not_yet_emitted"),
    RiskCodeEntry("CTX-TRACE-RELOAD", "", (), "main agent bulk re-reads historical messages because the Trace exists", (_DOC_06,), "not_yet_emitted"),
)

# context.models.assess_context also emits f-string rules for each metric in
# THRESHOLDED_CONTEXT_METRICS (loaded_chars, pinned_chars,
# skill_instruction_chars, recent_handoffs, open_items, turns,
# long_tool_outputs); these are not scannable literals and are recorded here
# for completeness.
DYNAMIC_CODE_FAMILIES: tuple[str, ...] = (
    "CTX-{metric}-WARN",
    "CTX-{metric}-ROLLOVER",
)
